##############################################################################################
# emart-backend-service
##############################################################################################
apiVersion: v1
kind: Service
metadata:
  name: emart-backend-service
  labels:
    app: emart-backend
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    name: 8080-http
    protocol: TCP
  selector:
    app: emart-backend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: emart-backend
  labels: 
    app: emart-backend
spec:
  replicas: 3
  selector: 
    matchLabels: 
      app: emart-backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: emart-backend
        version: v1
    spec:
      containers:
      - name: emart-backend
        image: image-registry.openshift-image-registry.svc:5000/cicd/emart-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
